export const PORTFOLIO_ITEMS = [
  { img: 'g1.jpg', category: 'gallery', title: 'Gallery' },
  { img: 'a1.jpg', category: 'activities', title: 'Activities' },
  { img: 'g3.jpg', category: 'gallery', title: 'Gallery' },
  { img: 'c1.jpg', category: 'certificate', title: 'ทักษะการเขียนโปรแกรมคอมพิวเตอร์ ระดับ ปวช. การแข่งขันทักษะวิชาชีพ ปี 2565' },
  { img: 'c2.jpg', category: 'certificate', title: 'หลักสูตรด้านความมั่นคงปลอดภัยไซเบอร์ระดับพื้นฐาน' },
  { img: 'g4.jpg', category: 'gallery', title: 'Gallery' },
  { img: 'c3.jpg', category: 'certificate', title: 'GLOBAL IT CHALLENGE FOR YOUTH WITH DISABILITIES' },
  { img: 'c4.jpg', category: 'certificate', title: 'WEB APPLICATION DEVELOPMENT' },
  { img: 'a5.jpg', category: 'activities', title: 'Activities' },
  { img: 'g5.jpg', category: 'gallery', title: 'Gallery' },
  { img: 'c5.jpg', category: 'certificate', title: 'PYTHON PROGRAMMING' },
  { img: 'c8.jpg', category: 'certificate', title: 'ทักษะการเขียนโปรแกรมคอมพิวเตอร์ ระดับ ปวส. การแข่งขันทักษะวิชาชีพ ปี 2567' },
  { img: 'g7.jpg', category: 'gallery', title: 'Gallery' },
  { img: 'a6.jpg', category: 'activities', title: 'Activities' },
  { img: 'c6.jpg', category: 'certificate', title: 'โครงการแนะแนวการศึกษาเพื่อพัฒนาอาชีพด้านความมั่นคงปลอดภัยไซเบอร์' },
  { img: 'a8.jpg', category: 'activities', title: 'Activities' },
  { img: 'g8.jpg', category: 'gallery', title: 'Gallery' },
  { img: 'c7.jpg', category: 'certificate', title: 'Thailand Cyber Top Talent 2023' },
  { img: 'a2.jpg', category: 'activities', title: 'Activities' },
  { img: 'g9.jpg', category: 'gallery', title: 'Gallery' },
  { img: 'a8.jpg', category: 'activities', title: 'Activities' },
  { img: 'g6.jpg', category: 'gallery', title: 'Gallery' },
  { img: 'a3.jpg', category: 'activities', title: 'Activities' },
  { img: 'c9.jpg', category: 'certificate', title: 'Thailand Cyber Top Talent 2024' },
  { img: 'c10.jpg', category: 'certificate', title: 'ผ่านการฝึกงานกับทางสำนักงานคณะกรรมการการรักษาความมั่นคงปลอดภัย (สกมช)' },
]
