export const PROJECTS = [
  {
    id: '001',
    cover: 'cover-ioc-tool.png',
    title: 'IOC Lookup Tool',
    role: 'Cybersecurity Intern',
    timeline: '2023 — Bangkok',
    status: 'Deployed internally',
    short: 'เครื่องมือตรวจสอบ IOC เทียบกับฐานข้อมูล threat intelligence',
    lead: 'CLI/เว็บเครื่องมือที่รับ IP, hash, domain แล้วเทียบกับฐานข้อมูล threat intel หลายแหล่งพร้อมกัน สรุปผลเป็น risk score เดียวให้ทีมอ่านง่าย',
    features: [
      'query พร้อมกันหลาย threat intel API (VirusTotal, AbuseIPDB)',
      'normalize ผลลัพธ์เป็น risk score มาตรฐานเดียว',
      'cache ผลลัพธ์ลด rate limit จาก API ภายนอก',
    ],
    tags: ['Python', 'FastAPI', 'Redis', 'VirusTotal API', 'AbuseIPDB API'],
    links: [{ label: 'Internal tool — private' }],
  },
  {
    id: '002',
    cover: 'cover-phishing-detector.png',
    title: 'Phishing & Typosquatting Detector',
    role: 'Cybersecurity Intern',
    timeline: '2023 — Bangkok',
    status: 'Deployed internally',
    short: 'ตรวจจับเว็บไซต์ฟิชชิ่งและโดเมนแอบอ้างแบรนด์แบบอัตโนมัติ',
    lead: 'เครื่องมือสแกนโดเมนที่คล้ายกับแบรนด์องค์กร (typosquatting) และตรวจสอบหน้าเว็บที่เข้าข่ายฟิชชิ่ง จากนั้นส่ง alert ให้ทีมความปลอดภัยดำเนินการ takedown',
    features: [
      'คำนวณ domain similarity ด้วย Levenshtein + homograph check',
      'scrape และวิเคราะห์หน้าเว็บต้องสงสัยหา phishing pattern',
      'ส่ง report พร้อมหลักฐานให้ทีม takedown',
    ],
    tags: ['Python', 'Scrapy', 'Levenshtein', 'VirusTotal API', 'Cron'],
    links: [{ label: 'Case study' }],
  },
  {
    id: '003',
    cover: 'cover-data-leak-bot.png',
    title: 'Data Leak Monitoring Bot',
    role: 'Cybersecurity Intern',
    timeline: '2023 — Bangkok',
    status: 'Deployed internally',
    short: 'บอทเฝ้าระวังและแจ้งเตือนข้อมูลรั่วไหลแบบเรียลไทม์',
    lead: 'บอทที่เฝ้าดู paste site และ dark web forum หาคำที่เกี่ยวกับโดเมน/แบรนด์องค์กร แล้วแจ้งเตือนทันทีผ่าน Line/Slack เมื่อพบข้อมูลที่อาจรั่วไหล',
    features: [
      'เฝ้าระวัง paste site / forum แบบ real-time',
      'กรอง false positive ด้วย keyword scoring',
      'แจ้งเตือนทันทีผ่าน Line Notify และ Slack webhook',
    ],
    tags: ['Python', 'Selenium', 'Redis', 'Line Notify API', 'Slack API'],
    links: [{ label: 'Case study' }],
  },
  {
    id: '004',
    cover: 'cover-motorbike-system.png',
    title: 'Motorbike Business Internal System',
    role: 'Programmer',
    timeline: '2022 — Maha Sarakham',
    status: 'Live in production',
    short: 'ระบบจัดการงานภายในสำหรับธุรกิจมอเตอร์ไซค์ ดูแลร่วมกับทีม',
    lead: 'พัฒนาและดูแลระบบหลังบ้านสำหรับธุรกิจมอเตอร์ไซค์ ครอบคลุมสต็อก การขาย และข้อมูลลูกค้า ทำงานร่วมกับทีมเพื่อแก้ปัญหาหน้างานและปรับปรุงให้ใช้งานได้ต่อเนื่อง',
    features: [
      'จัดการสต็อกสินค้าและใบสั่งซื้อ',
      'ระบบขายหน้าร้านเชื่อมกับข้อมูลลูกค้า',
      'แก้ไขบั๊กและปรับปรุงระบบตามฟีดแบ็กผู้ใช้จริง',
    ],
    tags: ['PHP', 'MySQL', 'jQuery', 'Bootstrap'],
    links: [{ label: 'Internal system — private' }],
  },
  {
    id: '005',
    cover: 'cover-thai-post.png',
    title: 'Thailand Post System Contribution',
    role: 'Software Dev Intern',
    timeline: '2022 — Pattaya',
    status: 'Shipped',
    short: 'มีส่วนร่วมพัฒนาระบบไปรษณีย์ไทยด้วย Vue.js และ .NET',
    lead: 'ร่วมทีมพัฒนาโมดูลของระบบไปรษณีย์ไทย ฝั่ง frontend ด้วย Vue.js เชื่อมต่อ backend .NET API ภายใต้ codebase ระดับองค์กรที่มีทีมใหญ่ร่วมดูแล',
    features: [
      'พัฒนา UI component ด้วย Vue.js ตาม design spec องค์กร',
      'เชื่อมต่อและทดสอบ .NET Web API',
      'ทำงานร่วมกับทีมใหญ่ภายใต้ git workflow มาตรฐานองค์กร',
    ],
    tags: ['Vue.js', '.NET', 'C#', 'SQL Server', 'Git'],
    links: [{ label: 'Enterprise project — private' }],
  },
  {
    id: '006',
    cover: 'cover-threat-intel.png',
    title: 'Cyber Threat Intelligence Tracker',
    role: 'Cybersecurity Intern',
    timeline: '2023 — Bangkok',
    status: 'Deployed internally',
    short: 'AI/NLP system tracking cyber threat intel feeds to support SOC operations.',
    lead: 'ระบบติดตามข่าวกรองภัยคุกคามไซเบอร์ที่ใช้ AI และ NLP วิเคราะห์ feed ข่าว/forum/paste site แบบอัตโนมัติ แล้วสรุปเป็น threat report ให้ทีม SOC ใช้ตัดสินใจเร็วขึ้น',
    features: [
      'ดึงข้อมูลจากหลายแหล่ง (RSS, forum, paste site) แบบ schedule',
      'ใช้ NLP จัดกลุ่ม/สรุปเนื้อหาข่าวภัยคุกคามอัตโนมัติ',
      'แจ้งเตือนทีมผ่าน dashboard เมื่อพบ keyword เสี่ยง',
    ],
    tags: ['Python', 'NLP', 'spaCy', 'PostgreSQL', 'Docker', 'REST API'],
    links: [{ label: 'Case study' }],
  },
  {
    id: '007',
    cover: 'cover-ioc-tool.png',
    title: 'Mock Project Seven',
    role: 'Developer',
    timeline: '2024',
    status: 'Demo',
    short: 'ข้อมูลจำลองสำหรับทดสอบ layout การ์ดที่ 7',
    lead: 'ข้อความจำลองเพื่อดูว่า bento grid จัดวางยังไงเมื่อมีการ์ดจำนวนมาก',
    features: ['ฟีเจอร์จำลอง A', 'ฟีเจอร์จำลอง B'],
    tags: ['Mock', 'Test'],
    links: [{ label: 'Demo' }],
  },
  {
    id: '008',
    cover: 'cover-phishing-detector.png',
    title: 'Mock Project Eight',
    role: 'Developer',
    timeline: '2024',
    status: 'Demo',
    short: 'ข้อมูลจำลองสำหรับทดสอบ layout การ์ดที่ 8',
    lead: 'ข้อความจำลองเพื่อดูว่า bento grid จัดวางยังไงเมื่อมีการ์ดจำนวนมาก',
    features: ['ฟีเจอร์จำลอง A', 'ฟีเจอร์จำลอง B'],
    tags: ['Mock', 'Test'],
    links: [{ label: 'Demo' }],
  },
  {
    id: '009',
    cover: 'cover-data-leak-bot.png',
    title: 'Mock Project Nine',
    role: 'Developer',
    timeline: '2024',
    status: 'Demo',
    short: 'ข้อมูลจำลองสำหรับทดสอบ layout การ์ดที่ 9',
    lead: 'ข้อความจำลองเพื่อดูว่า bento grid จัดวางยังไงเมื่อมีการ์ดจำนวนมาก',
    features: ['ฟีเจอร์จำลอง A', 'ฟีเจอร์จำลอง B'],
    tags: ['Mock', 'Test'],
    links: [{ label: 'Demo' }],
  },
  {
    id: '010',
    cover: 'cover-motorbike-system.png',
    title: 'Mock Project Ten',
    role: 'Developer',
    timeline: '2024',
    status: 'Demo',
    short: 'ข้อมูลจำลองสำหรับทดสอบ layout การ์ดที่ 10',
    lead: 'ข้อความจำลองเพื่อดูว่า bento grid จัดวางยังไงเมื่อมีการ์ดจำนวนมาก',
    features: ['ฟีเจอร์จำลอง A', 'ฟีเจอร์จำลอง B'],
    tags: ['Mock', 'Test'],
    links: [{ label: 'Demo' }],
  },
]
