export const PROJECTS = [
  {
    id: '001',
    cover: 'cover-ioc-tool.png',
    title: 'IOC Lookup Tool',
    role: 'Cybersecurity Intern',
    timeline: '2023 — Bangkok',
    status: 'Deployed internally',
    short: 'เครื่องมือตรวจสอบ IOC เทียบกับฐานข้อมูล threat intelligence',
    lead: 'CLI/เว็บเครื่องมือที่รับ IP, hash, domain แล้วเทียบกับฐานข้อมูล threat intel หลายแหล่งพร้อมกัน สรุปผลเป็น risk score เดียวให้ทีมอ่านง่าย',
    features: [
      'query พร้อมกันหลาย threat intel API (VirusTotal, AbuseIPDB)',
      'normalize ผลลัพธ์เป็น risk score มาตรฐานเดียว',
      'cache ผลลัพธ์ลด rate limit จาก API ภายนอก',
    ],
    tags: ['Python', 'FastAPI', 'Redis', 'VirusTotal API', 'AbuseIPDB API'],
    links: [{ label: 'Internal tool — private' }],
  },
  {
    id: '002',
    cover: 'cover-phishing-detector.png',
    title: 'Phishing & Typosquatting Detector',
    role: 'Cybersecurity Intern',
    timeline: '2023 — Bangkok',
    status: 'Deployed internally',
    short: 'ตรวจจับเว็บไซต์ฟิชชิ่งและโดเมนแอบอ้างแบรนด์แบบอัตโนมัติ',
    lead: 'เครื่องมือสแกนโดเมนที่คล้ายกับแบรนด์องค์กร (typosquatting) และตรวจสอบหน้าเว็บที่เข้าข่ายฟิชชิ่ง จากนั้นส่ง alert ให้ทีมความปลอดภัยดำเนินการ takedown',
    features: [
      'คำนวณ domain similarity ด้วย Levenshtein + homograph check',
      'scrape และวิเคราะห์หน้าเว็บต้องสงสัยหา phishing pattern',
      'ส่ง report พร้อมหลักฐานให้ทีม takedown',
    ],
    tags: ['Python', 'Scrapy', 'Levenshtein', 'VirusTotal API', 'Cron'],
    links: [{ label: 'Case study' }],
  },
  {
    id: '003',
    cover: 'cover-data-leak-bot.png',
    title: 'Data Leak Monitoring Bot',
    role: 'Cybersecurity Intern',
    timeline: '2023 — Bangkok',
    status: 'Deployed internally',
    short: 'บอทเฝ้าระวังและแจ้งเตือนข้อมูลรั่วไหลแบบเรียลไทม์',
    lead: 'บอทที่เฝ้าดู paste site และ dark web forum หาคำที่เกี่ยวกับโดเมน/แบรนด์องค์กร แล้วแจ้งเตือนทันทีผ่าน Line/Slack เมื่อพบข้อมูลที่อาจรั่วไหล',
    features: [
      'เฝ้าระวัง paste site / forum แบบ real-time',
      'กรอง false positive ด้วย keyword scoring',
      'แจ้งเตือนทันทีผ่าน Line Notify และ Slack webhook',
    ],
    tags: ['Python', 'Selenium', 'Redis', 'Line Notify API', 'Slack API'],
    links: [{ label: 'Case study' }],
  },
  {
    id: '004',
    cover: 'cover-motorbike-system.png',
    title: 'Motorbike Business Internal System',
    role: 'Programmer',
    timeline: '2022 — Maha Sarakham',
    status: 'Live in production',
    short: 'ระบบจัดการงานภายในสำหรับธุรกิจมอเตอร์ไซค์ ดูแลร่วมกับทีม',
    lead: 'พัฒนาและดูแลระบบหลังบ้านสำหรับธุรกิจมอเตอร์ไซค์ ครอบคลุมสต็อก การขาย และข้อมูลลูกค้า ทำงานร่วมกับทีมเพื่อแก้ปัญหาหน้างานและปรับปรุงให้ใช้งานได้ต่อเนื่อง',
    features: [
      'จัดการสต็อกสินค้าและใบสั่งซื้อ',
      'ระบบขายหน้าร้านเชื่อมกับข้อมูลลูกค้า',
      'แก้ไขบั๊กและปรับปรุงระบบตามฟีดแบ็กผู้ใช้จริง',
    ],
    tags: ['PHP', 'MySQL', 'jQuery', 'Bootstrap'],
    links: [{ label: 'Internal system — private' }],
  },
  {
    id: '005',
    cover: 'cover-thai-post.png',
    title: 'Thailand Post System Contribution',
    role: 'Software Dev Intern',
    timeline: '2022 — Pattaya',
    status: 'Shipped',
    short: 'มีส่วนร่วมพัฒนาระบบไปรษณีย์ไทยด้วย Vue.js และ .NET',
    lead: 'ร่วมทีมพัฒนาโมดูลของระบบไปรษณีย์ไทย ฝั่ง frontend ด้วย Vue.js เชื่อมต่อ backend .NET API ภายใต้ codebase ระดับองค์กรที่มีทีมใหญ่ร่วมดูแล',
    features: [
      'พัฒนา UI component ด้วย Vue.js ตาม design spec องค์กร',
      'เชื่อมต่อและทดสอบ .NET Web API',
      'ทำงานร่วมกับทีมใหญ่ภายใต้ git workflow มาตรฐานองค์กร',
    ],
    tags: ['Vue.js', '.NET', 'C#', 'SQL Server', 'Git'],
    links: [{ label: 'Enterprise project — private' }],
  },
  {
    id: '006',
    cover: 'cover-threat-intel.png',
    title: 'Cyber Threat Intelligence Tracker',
    role: 'Cybersecurity Intern',
    timeline: '2023 — Bangkok',
    status: 'Deployed internally',
    short: 'AI/NLP system tracking cyber threat intel feeds to support SOC operations.',
    lead: 'ระบบติดตามข่าวกรองภัยคุกคามไซเบอร์ที่ใช้ AI และ NLP วิเคราะห์ feed ข่าว/forum/paste site แบบอัตโนมัติ แล้วสรุปเป็น threat report ให้ทีม SOC ใช้ตัดสินใจเร็วขึ้น',
    features: [
      'ดึงข้อมูลจากหลายแหล่ง (RSS, forum, paste site) แบบ schedule',
      'ใช้ NLP จัดกลุ่ม/สรุปเนื้อหาข่าวภัยคุกคามอัตโนมัติ',
      'แจ้งเตือนทีมผ่าน dashboard เมื่อพบ keyword เสี่ยง',
    ],
    tags: ['Python', 'NLP', 'spaCy', 'PostgreSQL', 'Docker', 'REST API'],
    links: [{ label: 'Case study' }],
  },
  {
    id: '007',
    cover: 'cover-piya-skill.png',
    title: 'piya-skill',
    role: 'Open Source Author',
    timeline: '2026 — Ongoing',
    status: 'Public on GitHub',
    short: 'คลัง skill สำหรับ AI coding agent เช่น Claude Code, Codex, Cursor',
    lead: 'คอลเลกชัน skill สำหรับ AI coding agent แต่ละตัวมี test กำกับ เริ่มจาก thai-natural-writing ที่เขียนภาษาไทยให้เป็นธรรมชาติ เลือก wording ตามกลุ่มผู้อ่าน พร้อมคงศัพท์เทคนิคที่นักพัฒนาไทยพูดทับศัพท์อยู่แล้ว',
    features: [
      'โหมดกลุ่มผู้อ่าน: General, Developer, Business, Documentation',
      'คงศัพท์เทคนิค (Architecture, API, Backend, Deploy) ไว้เป็นภาษาอังกฤษสำหรับสายเดฟ',
      'ตัด pattern ภาษาไทยแบบ AI ออก (ดำเนินการ, ทำการ, คำเปิดเรียงความ)',
      'benchmark วัดผล 93% pass rate เทียบ baseline 67%',
    ],
    tags: ['Markdown', 'Claude Code', 'Codex', 'Cursor', 'Prompt Engineering'],
    links: [{ label: 'View on GitHub', href: 'https://github.com/Piya-Boy/piya-skill', primary: true }],
  },
  {
    id: '008',
    cover: 'cover-agents-office.png',
    title: 'Agents Office',
    role: 'Open Source Author',
    timeline: '2026 — Ongoing',
    status: 'Working prototype',
    short: 'Desktop harness ที่รัน AI coding agent หลายตัวพร้อมกันบนออฟฟิศ 2D',
    lead: 'แอป Electron/React ที่ห่อ terminal coding agent CLI จริง (Claude Code, Codex, Gemini, Grok, Qwen ฯลฯ) ให้ทำงานเป็นทีมอัตโนมัติ แต่ละ agent มีหน่วยความจำระยะยาว กล่องจดหมาย และโต๊ะทำงานบนพื้นออฟฟิศ 2D ที่มองเห็นได้จริง โดยมี orchestrator agent ของผู้ใช้เองคอยจัดสรรงาน',
    features: [
      'ทุก terminal คือ agent จริงที่รันใน node-pty แล้วเรนเดอร์ด้วย xterm.js',
      'ทุก agent มี avatar เดินบนพื้นออฟฟิศ Pixi.js ส่งข้อความเป็นซองจดหมายบินข้ามโต๊ะ',
      'GOD orchestrator กระจายงาน ตัดสินใจเอง และ escalate เฉพาะเรื่องสำคัญให้มนุษย์',
      'Kanban board, budget/token ledger, และ Monaco IDE ในตัว',
    ],
    tags: ['Electron', 'React', 'TypeScript', 'Pixi.js', 'node-pty'],
    links: [{ label: 'View on GitHub', href: 'https://github.com/Piya-Boy/agents-office', primary: true }],
  },
  {
    id: '009',
    cover: 'cover-clawdclock.png',
    title: 'ClawdClock',
    role: 'Open Source Author',
    timeline: '2026',
    status: 'Released on GitHub',
    short: 'Windows screensaver ที่โชว์นาฬิกาแบบ flip-clock พร้อม usage ของ Claude Code',
    lead: 'แอป Tauri/Rust ที่เปลี่ยนหน้าจอว่างให้เป็นนาฬิกาพลิกใบขนาดใหญ่ พร้อมแสดง token usage ของ Claude Code แบบเรียลไทม์ ทั้งโควต้า session 5 ชั่วโมงและโควต้ารายสัปดาห์ 7 วัน ติดตั้งเป็น Windows screensaver (.scr) ได้จริง',
    features: [
      'นาฬิกาพลิกใบ (flip-clock) แบบ 9 ธีม รวม OLED black กันจอไหม้',
      'อ่าน Claude OAuth token จากเครื่องผู้ใช้เอง ไม่ส่งออกไปไหนนอกจาก API ของ Anthropic',
      'เปิดอัตโนมัติเมื่อเครื่อง idle, ล็อกหน้าจอกันมือลั่นปิดโดยไม่ตั้งใจ',
      'รองรับหลายจอ, global hotkey, auto-update',
    ],
    tags: ['Tauri', 'Rust', 'React', 'TypeScript', 'Zustand'],
    links: [{ label: 'View on GitHub', href: 'https://github.com/Piya-Boy/ClawdClock', primary: true }],
  },
  {
    id: '010',
    cover: 'cover-course-platform.png',
    title: 'Course Platform',
    role: 'Open Source Author',
    timeline: '2025',
    status: 'Public on GitHub',
    short: 'แพลตฟอร์มคอร์สออนไลน์สไตล์ Udemy สร้างด้วย Next.js',
    lead: 'ระบบจัดการคอร์สออนไลน์ให้ผู้สอนสร้างคอร์ส เพิ่มบทเรียนวิดีโอ จัดลำดับบทด้วยการลากวาง และเผยแพร่คอร์ส ส่วนผู้เรียนสมัครเรียนและติดตามความคืบหน้า ระบบยืนยันตัวตนด้วย Clerk สตรีมวิดีโอผ่าน Mux และเก็บข้อมูลด้วย Prisma',
    features: [
      'ลากวางจัดลำดับบทเรียนด้วย drag-and-drop',
      'สตรีมวิดีโอบทเรียนผ่าน Mux พร้อม progress tracking',
      'เช็กลิสต์ก่อนเผยแพร่คอร์ส (title, pricing, chapter ครบ)',
      'ยืนยันตัวตนผู้สอน/ผู้เรียนด้วย Clerk',
    ],
    tags: ['Next.js', 'Prisma', 'Clerk', 'Mux', 'TypeScript'],
    links: [{ label: 'View on GitHub', href: 'https://github.com/Piya-Boy/Course-Platform', primary: true }],
  },
  {
    id: '011',
    cover: 'cover-security-news-dashboard.png',
    title: 'Security News Analysis Dashboard',
    role: 'Open Source Author',
    timeline: '2025',
    status: 'Public on GitHub',
    short: 'Dashboard วิเคราะห์ข่าวความปลอดภัยไซเบอร์ด้วย NLP',
    lead: 'ระบบ scraper ดึงข่าวความปลอดภัยไซเบอร์จากหลายแหล่ง จัดหมวดประเภทการโจมตีด้วย NLP (NLTK, transformers) แล้วแสดงผลเป็น dashboard Streamlit ที่กรองตามเดือน ปี และประเภทการโจมตี พร้อม export ข้อมูลเป็น CSV, JSON หรือ Excel',
    features: [
      'กราฟแนวโน้มประเภทการโจมตีตามเวลา และกราฟสัดส่วน/รายปี',
      'จัดหมวดบทความอัตโนมัติด้วย transformer model',
      'กรองข้อมูลตามเดือน ปี และประเภทการโจมตี',
      'export ชุดข้อมูลเป็น CSV, JSON, Excel',
    ],
    tags: ['Python', 'Streamlit', 'Plotly', 'NLTK', 'Flask'],
    links: [{ label: 'View on GitHub', href: 'https://github.com/Piya-Boy/Security-News-Analysis-Dashboard', primary: true }],
  },
]
